name: job_spot
description: Find Your Dream Job Here!

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.5"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.1+1
  google_fonts: ^3.0.1
  sailor: ^0.7.1
  fluro: ^2.0.3
  url_launcher: ^6.1.5
  google_maps_flutter: ^2.1.10
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.0
  flutter_bloc: ^8.0.1
  keyboard_service: ^2.0.2
  either_dart: ^0.2.0
  logger: ^1.1.0
  floading: ^2.0.0
  faker_dart: ^0.1.6
  equatable: ^2.0.3
  cached_network_image: ^3.2.1
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svgs/
    - assets/images/pngs/
