import 'package:flutter/material.dart';

const darkIndigo = Color(0xff160064);
const transCongressBlue = Color(0x44014099);
const spanPearl = Color(0xffAAA6B9);
const lavenderMist = Color(0xffE6E1FF);
const mercuryBlue = Color(0xffe5e5e5);
const nightBlue = Color(0xff0D0140);
const orangeDeepSaffron = Color(0xffFF9228);
const fog = Color(0xffd8cdff);
const mulledWine = Color(0xff524B6B);
const purpleBlueMoonraker = Color(0xffD6CDFE);
const deepViolet = Color(0xff130160);
const bluishCyanFrenchPass = Color(0xffAFECFE);
const neonCarrot = Color(0xffFCA34D);
const whiteSnowDrift = Color(0xfff9f9f9);
const violetPale = Color(0xffBEAFFE);
const orangeLightApricot = Color(0xffFFD6AD);
const lightRed = Color(0xffFC4646);
const bluePurpleAmethystSmoke = Color(0xff9D97B5);
const antiFlashWhite = Color(0xfff0eef9);
const grayGhost = Color(0xffCBC9D4);
const orangeBurning = Color(0xffFF6B2C);
const blackHaiti = Color(0xff150B3D);
const blueLotus = Color(0xff7551FF);
const tealishBlue = Color(0xffDEE1E7);
